### ISSUE TITLE
Initial Build

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-zendesk-source#1]
**Background**
The existing Node package (below) looks fairly robust so this should be a relatively easy build. We're only building out the Core API for now.

**Requirements**
- Build methods for `list` from the following endpoints:
  - [ ] [Activity Stream](https://developer.zendesk.com/rest_api/docs/core/activity_stream)
  - [ ] [Tickets](https://developer.zendesk.com/rest_api/docs/core/tickets)
  - [ ] [Ticket Metrics](https://developer.zendesk.com/rest_api/docs/core/ticket_metrics)
  - [ ] [Ticket Forms](https://developer.zendesk.com/rest_api/docs/core/ticket_forms)
  - [ ] [Users](https://developer.zendesk.com/rest_api/docs/core/users)
  - [ ] [Groups](https://developer.zendesk.com/rest_api/docs/core/groups)
  - [ ] [Group Memberships](https://developer.zendesk.com/rest_api/docs/core/group_memberships)
  - [ ] [Tags](https://developer.zendesk.com/rest_api/docs/core/tags)
  - [ ] [Schedules](https://developer.zendesk.com/rest_api/docs/core/schedules)
  - [ ] [Satisfaction Ratings](https://developer.zendesk.com/rest_api/docs/core/satisfaction_ratings)
  - [ ] [Sessions](https://developer.zendesk.com/rest_api/docs/core/sessions)
  - [ ] [Brands](https://developer.zendesk.com/rest_api/docs/core/brands)
  - [ ] [Support Addresses](https://developer.zendesk.com/rest_api/docs/core/support_addresses)
  - [ ] [Twitter](https://developer.zendesk.com/rest_api/docs/core/twitter_channel)

**Relevant Links**
https://developer.zendesk.com/rest_api/docs/api-clients/nodejs
https://www.npmjs.com/package/node-zendesk

**Comment by benjamingregory** [comment]
@noahbass When you can, please leave a progress update on where this stands.

**Comment by noahbass** [comment]
2017.01.12 - 11 of the 14 required methods are ready. 3 of them (brands, support addresses, and twitter) are unsupported by the node-zendesk module, so I'm doing a workaround for those methods.

**Comment by noahbass** [comment]
2017.01.15 - all required methods are ready. Pull request coming asap.

**Comment by benjamingregory** [comment]
@noahbass When the PR is created, please move this to Done

**Comment by noahbass** [comment]
2017.01.17 - PR in. See #2
